name: Update MAL Anime List

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install beautifulsoup4 requests

      - name: Update README
        run: python update_mal.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add README.md

          git diff --quiet && git diff --staged --quiet || git commit -m "Update MAL"

          git push
